[package]
name = "cut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.13"
indoc = "2.0.4"
predicates = "3.1.0"
