name: Build Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Test ${{ matrix.component }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [wc, json-parser]

    defaults:
      run:
        working-directory: ./${{ matrix.component }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
